#!/usr/bin/env python

import kcho_eddy
import eddy_plots
from pathlib import Path
import os
import argparse
from tabulate import tabulate

if __name__ == '__main__':
    argparser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description='''\
        eddy_squeeze.
        Visualize extra information from FSL eddy outputs.
        ''', epilog="Kevin Cho November 30, 2019")

    argparser.add_argument("--eddy_dir", "-ed",
                           type=str,
                           default=os.getcwd(),
                           help='Eddy output directory. Default = current '
                                'directory')

    argparser.add_argument("--out_dir", "-od",
                           type=str,
                           help='Eddy output directory. Default = '
                                '/PATH/TO/EDDY/outlier_figures')

    argparser.add_argument("--print_only", "-po",
                           action='store_true',
                           help='Eddy output directory')

    argparser.add_argument("--save_csv", "-sc",
                           action='store_true',
                           help='Save eddy information to csv file')

    argparser.add_argument("--save_html", "-sh",
                           action='store_true',
                           help='Save eddy information to html file')

    argparser.add_argument("--study_dir", "-sd",
                           type=str,
                           default=os.getcwd(),
                           help='Directory path pattern where are more than '
                                'one Eddy output directories')

    args = argparser.parse_args()

    # set output directories
    if not args.out_dir:
        args.out_dir = Path(args.eddy_dir) / 'outlier_figures'

    if args.eddy_dir and not args.print_only:
        eddyOut = eddy_plots.EddyFigure(
            args.eddy_dir,
            args.out_dir)
        eddyOut.save_all_outlier_slices()

    elif args.eddy_dir and args.print_only:
        eddyOut = eddy_plots.EddyFigure(
            args.eddy_dir,
            args.out_dir)


        eddyOut.summary_df()
        print('Eddy head motion summary')
        print('-'*50)
        print(tabulate(eddyOut.df_motion, headers='keys', tablefmt='github'))
        print()
        print('Outlier slice summary')
        print('-'*50)
        print(tabulate(eddyOut.df, headers='keys', tablefmt='github'))
        print()

        # post eddy shell alignment information
        print('Post eddy shell alignment information')
        print('-'*50)
        print(tabulate(eddyOut.post_eddy_shell_alignment_df, headers='keys', tablefmt='psql'))
        print()

        # post eddy shell PE translation information
        print('Post eddy shell PE translation information')
        print('-'*50)
        print(tabulate(eddyOut.post_eddy_shell_PE_translation_parameters_df, headers='keys', tablefmt='psql'))
        print()

        if args.save_csv:
            eddyOut.df_motion.to_csv(args.out_dir / 'motion.csv')
            eddyOut.df.to_csv(args.out_dir / 'outlier_slices.csv')

