#!/usr/bin/env python

import kcho_eddy
import eddy_plots
from pathlib import Path
import os
import argparse
from tabulate import tabulate

if __name__ == '__main__':
    argparser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description='''\
        eddy_squeeze.
        Visualize extra information from FSL eddy outputs.
        ''', epilog="Kevin Cho November 30, 2019")

    argparser.add_argument("--study_dir", "-sd",
                           type=str,
                           default=os.getcwd(),
                           help='Directory path where there are more than '
                                'one eddy output directories')

    argparser.add_argument("--eddy_pattern", "-ep",
                           type=str,
                           help='Pattern of eddy directories')

    args = argparser.parse_args()

    # set output directories
    eddyStudy = kcho_eddy.EddyStudy(args.eddy_pattern)
    eddyStudy.clean_up_data_frame()
    df = eddyStudy.df.sort_values(
        ['number of outlier slices',
         'Sum of standard deviations in outlier slices',
         'absolute restricted movement',
         'relative restricted movement'], ascending=False).drop(
             ['ep', 'eddy_dir', 'unique b values', 'eddy_input'],
             axis=1).reset_index().drop('index', axis=1)

    print(tabulate(df, headers='keys', tablefmt='psql'))
